### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by vanhauser-thc** [trailofbits/Honeybee#2]
```
$ cmake .
-- Configuring done
-- Generating done
-- Build files have been written to: /prg/tmp/Honeybee

$ make
[  5%] Building C object CMakeFiles/honey_analyzer.dir/honey_analyzer/trace_analysis/ha_session.c.o
[ 10%] Building C object CMakeFiles/honey_analyzer.dir/honey_analyzer/processor_trace/ha_pt_decoder.c.o
[ 15%] Building C object CMakeFiles/honey_analyzer.dir/honey_analyzer/capture/ha_capture_session.c.o
[ 21%] Building C object CMakeFiles/honey_analyzer.dir/honeybee_shared/hb_hive.c.o
[ 26%] Linking C static library libhoney_analyzer.a
[ 26%] Built target honey_analyzer
Scanning dependencies of target honey_coverage
[ 31%] Building C object CMakeFiles/honey_coverage.dir/honey_coverage/main.c.o
[ 36%] Building C object CMakeFiles/honey_coverage.dir/honey_coverage/hc_tree_set.c.o
[ 42%] Linking C executable honey_coverage
/bin/ld: cannot open output file honey_coverage: Is a directory
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/honey_coverage.dir/build.make:119: honey_coverage] Error 1
make[1]: *** [CMakeFiles/Makefile2:101: CMakeFiles/honey_coverage.dir/all] Error 2
make: *** [Makefile:103: all] Error 2
```
Also this build command in the README is incorrect:
```
$ cmake --build cmake-build-debug
Error: /prg/tmp/Honeybee/cmake-build-debug is not a directory
```
And there is a left over file: `dependencies/build_depencies.sh`

thank you!

**Comment by ezhes** [comment]
You need to make a folder for the build artifacts, `mkdir cmake-build-debug`. The linker error is because it looks like you're build in the root directory (which is not supported) and the linker is trying to link one of the source folders into a binary of the same name. 

>And there is a left over file: `dependencies/build_depencies.sh`

Oops, thank you. Managed to miss adding that delete to the commit!

**Comment by vanhauser-thc** [comment]
I had tried that too:
```
$ mkdir cmake-build-debug
$ cmake --build cmake-build-debug
Error: could not load cache
```
I kinda hate cmake, and I think for a cmake user it is obvious what is the right way ...
```
mkdir build
cd build
cmake ..
make
```
doesnt work either

**Comment by ezhes** [comment]
Hmm I definitely didn't thoroughly test building I guess. 

I was just able to build from scratch with this:

1. `git clone https://github.com/trailofbits/Honeybee.git`
2. `cd dependencies; ./build_dependencies; cd ../`
3. `mkdir cmake_build_debug; cd cmake_build_debug; cmake ..; cmake --build . --target all`

**Comment by vanhauser-thc** [comment]
yes, that worked, thank you!
In case you want to put that in the README,  ".sh" is missing from the build_dependencies script name
