### ISSUE TITLE
[Question] Which CPU for the most number of ip filtering range ?

### ISSUE THREAD

**Issue by zuypt** [trailofbits/Honeybee#5]
As the tiltle do you know which processor have the most number of ip filtering range (4) ? I checked the lastest core i9 11th gen but they only seem to support 2.

**Comment by ezhes** [comment]
This is sort of a pain to try and figure out, but my personal laptop has an i9-9880H which supports four IP filter ranges.

**Comment by zuypt** [comment]
Thanks for your time. Do you know any desktop processor that also support 4 ?
